### ISSUE TITLE
Can't connect to the dataset

### ISSUE THREAD

**Issue by GuoCHance** [MeteorsHub/GLIA-Net#10]

**Comment by GuoCHance** [comment]
cellpatterns 166.111.72.183, any wrong with the server?

**Comment by MeteorsHub** [comment]
Sorry but we got a security problem on the server and our engineer is fixing it. It should be OK by this month.

**Comment by MeteorsHub** [comment]
The data is ready now. Please see http://39.98.209.108/seafile/d/34d94c4bc44a42fdb33d/
