### ISSUE TITLE
How to decide whether the predict target match the ground truth?

### ISSUE THREAD

**Issue by Yashi-Nan** [MeteorsHub/GLIA-Net#11]
Hi, when evaluating performance on target level, what rule u use to see whether 'predict' and 'ground truth' are matched?
I found code related to the judgement in metrics.py. but what exactly it measures?

    def _is_match(center_1, area_1, center_2, area_2):
        ndim = len(center_1)
        if sum([(center_1[i] - center_2[i]) ** 2 for i in range(ndim)]) ** 0.5 < (
                0.62 * (area_1 ** (1 / ndim) + area_2 ** (1 / ndim))):  # for 3d case using 0.62 factor
            return True
        return False

**Comment by MeteorsHub** [comment]
You can compute the result yourself. It means the distance of two centers should be less than about half the radius of two objects (assume they are all spheres)
