### ISSUE TITLE
Can't connect to the dataset

### ISSUE THREAD

**Issue by haha9464** [MeteorsHub/GLIA-Net#13]
Hey, I tried many times but I still can't download your datasets according to tips you offered on 25 Jan.
So could you please provide another ip.
Thanks a lot!

**Comment by MeteorsHub** [comment]
Sorry for the issue. The data server went wrong recently. We are trying to find a new data host destination

**Comment by haha9464** [comment]
Thanks for your replying. Please let me konw if the dataset can be download. (*^_^*)

**Comment by MeteorsHub** [comment]
The dataset has been moved to Zenodo: https://doi.org/10.5281/zenodo.6801398
