### ISSUE TITLE
Is the released checkpoint the best chekpoint to obtain the published performance?

### ISSUE THREAD

**Issue by PRESENT-Y** [MeteorsHub/GLIA-Net#14]
I test the released checkpoint on the internal test set, however, the performance drops a lot compared with the performance in the published paper. I wonder how I reproduce the published performance. Retrain?

**Comment by MeteorsHub** [comment]
The checkpoint is already good in performance. 
You should use evaluate_per_case to test the overall performance. Because using evaluate.py directly is a test on patches, which highly depends on the patchify procedure.
Please see the readme.md for details on how to run evaluate_per_case
