### ISSUE TITLE
Clarification Needed on is_ruptured in internal_instances.csv for Subjects with Multiple IAs

### ISSUE THREAD

**Issue by AliJ9** [MeteorsHub/GLIA-Net#18]
In the `internal_instances.csv` file, for cases where a subject has more than one intracranial aneurysm (IA), if `is_ruptured` is set to yes, does this indicate that all the IAs for that specific subject are ruptured? If not, how can we determine which of those IAs are ruptured and which are unruptured?

Thanks!

**Comment by MeteorsHub** [comment]
Hi. If is_ruptured is set to yes, there are at least one IA is ruptured. But our annotation procedure did not offer information which one is ruptured if there are more than one IAs. We are sorry for the inconvenience.
