### ISSUE TITLE
RuntimeError: Given input size: (64x1x1x1). Calculated output size: (64x0x0x0). Output size is too small

### ISSUE THREAD

**Issue by zhang5957** [MeteorsHub/GLIA-Net#5]
I used the default parameters and 512 * 512 image training，and still got the error

**Comment by zhang5957** [comment]
I printed the size of the input data before entering the model，it shows torch.Size([3, 4, 4, 4]). And no matter how I modify the patch size, it doesn't change,can you help me?

**Comment by MeteorsHub** [comment]
You should make sure your data format is correct. If not, you can debug in the dataloader file
