### ISSUE TITLE
152 internal test dataset missing

### ISSUE THREAD

**Issue by Eason97** [MeteorsHub/GLIA-Net#6]
Thanks for sharing the dataset and thanks for your work. I have download the 1186 internal training data from the server, but I did not find the 152 internal test data. Can you share the test data on the server, thank you so much!

**Comment by MeteorsHub** [comment]
Sorry for the data missing problem. It is now available on our server

**Comment by Eason97** [comment]
Thank you so much!

**Comment by Eason97** [comment]
Sorry to bother you again. I download all the Internal dataset, but it seems that some cases are missing. Specifically, in Internal training dataset, case 348 to 406 are missing. In Internal test dataset, case 80 to 83 are missing. Can you share these samples, thank you.

**Comment by MeteorsHub** [comment]
It should be fine now

**Comment by Eason97** [comment]
wow! really appreciate
