### ISSUE TITLE
Is there somthing wrong with case Tr1058?

### ISSUE THREAD

**Issue by CarolRen233** [MeteorsHub/GLIA-Net#9]
I found the annotation of Tr1058 is located on the neck rather than the brain of the man. Is it abnormal?

![image](https://user-images.githubusercontent.com/25131143/144740977-c05fec67-1e05-48a2-b0d0-6a4ff0a37830.png)

**Comment by MeteorsHub** [comment]
This is still an aneurysm but not an intracranial one. Though we expect all our data are intracranial ones, but you can still use it because it shares the aneurysm features and the occurrence is very rare.
